create table if not exists candidate_profiles (
  telegram_user_id bigint primary key,
  display_name text,
  resume_file_name text,
  resume_mime_type text,
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists jobs (
  fingerprint text primary key,
  source text not null,
  source_job_id text,
  title text not null,
  company text not null,
  location text,
  description text,
  canonical_url text not null,
  employment_type text,
  track text,
  discovered_at timestamptz not null default now()
);

create table if not exists job_deliveries (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  job_fingerprint text not null references jobs(fingerprint) on delete cascade,
  match_score integer not null check (match_score between 0 and 100),
  sent_at timestamptz not null default now(),
  unique (telegram_user_id, job_fingerprint)
);

create index if not exists idx_jobs_track_discovered on jobs(track, discovered_at desc);
create index if not exists idx_deliveries_user_sent on job_deliveries(telegram_user_id, sent_at desc);
